services:
  pgdatabase:
    image: postgres:13
    environment:
      - name=value
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      # - airflow
      - metabase
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - "8080:80"
  
# networks:
#     my-proxy-net:
#     airflow:
#       name: airflow_default

networks:
    my-proxy-net:
    metabase:
      name: compose-postgres-metabase_default    
    
   #evironment mapping volumes ..host path